"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Check, Clock, Copy, Download, KeyRound, LogOut, Mail, Package, ShieldAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { formatPrice } from "@/lib/types";

type Event = { id: string; label: string; actor: string; createdAt: string };
type Claim = { id: string; status: string; reason: string; message: string; adminNote?: string | null; createdAt: string };
type Order = { id: string; productTitle: string; productCategory?: string; amount: number; currency: string; paymentMethod: string; status: string; createdAt: string; login?: string; password?: string; deliveryNote?: string; events: Event[]; warrantyUntil: string; claims: Claim[] };

const STATUS: Record<string, string> = { pending: "Ожидает оплаты", paid: "Оплата подтверждена", delivered: "Данные выданы", cancelled: "Отменён", archived: "Завершён" };
const REASONS = { login: "Не получается войти", password: "Неверный пароль", verification: "Запрашивается подтверждение", mismatch: "Не соответствует описанию", blocked: "Аккаунт заблокирован", other: "Другая проблема" };

export function AccountClient({ settings }: { settings: Record<string, string> }) {
  const [email, setEmail] = useState(""); const [code, setCode] = useState(""); const [orderId, setOrderId] = useState("");
  const [authenticated, setAuthenticated] = useState(false); const [emailConfigured, setEmailConfigured] = useState<boolean | null>(null);
  const [orders, setOrders] = useState<Order[]>([]); const [loading, setLoading] = useState(true); const [claimOrder, setClaimOrder] = useState<string | null>(null);
  const [reason, setReason] = useState<keyof typeof REASONS>("login"); const [message, setMessage] = useState(""); const { toast } = useToast();

  const loadOrders = async () => { const res = await fetch("/api/orders/by-email"); if (!res.ok) return; const data = await res.json(); setOrders(data.orders || []); setAuthenticated(true); };
  useEffect(() => { fetch("/api/customer-auth/session").then(async r => { if (r.ok) { const d = await r.json(); setEmail(d.email); await loadOrders(); } }).finally(() => setLoading(false)); }, []);
  const requestCode = async () => { setLoading(true); const res = await fetch("/api/customer-auth/request-code", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email }) }); const data = await res.json(); setLoading(false); if (!res.ok) return toast({ title: "Ошибка", description: data.error, variant: "destructive" }); setEmailConfigured(data.emailConfigured); toast({ title: data.emailConfigured ? "Код отправлен" : "Вход по номеру заказа", description: data.emailConfigured ? "Проверьте почту" : "Почтовая отправка пока не подключена" }); };
  const login = async () => { setLoading(true); const res = await fetch("/api/customer-auth/verify", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, code: code || undefined, orderId: orderId || undefined }) }); const data = await res.json(); if (res.ok) await loadOrders(); else toast({ title: "Вход не выполнен", description: data.error, variant: "destructive" }); setLoading(false); };
  const logout = async () => { await fetch("/api/customer-auth/session", { method: "DELETE" }); setAuthenticated(false); setOrders([]); setCode(""); setOrderId(""); };
  const copy = (value: string) => navigator.clipboard.writeText(value).then(() => toast({ title: "Скопировано" }));
  const download = (o: Order) => { const text = `HypeHub — данные заказа ${o.id}\nТовар: ${o.productTitle}\nЛогин: ${o.login}\nПароль: ${o.password}\n${o.deliveryNote || ""}\n\nСразу смените пароль, контакты и включите двухфакторную защиту.`; const url = URL.createObjectURL(new Blob([text], { type: "text/plain;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = `hypehub_${o.id}.txt`; a.click(); URL.revokeObjectURL(url); };
  const sendClaim = async () => { if (!claimOrder) return; const res = await fetch("/api/warranty", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ orderId: claimOrder, reason, message }) }); const data = await res.json(); if (!res.ok) return toast({ title: "Не отправлено", description: data.error, variant: "destructive" }); setClaimOrder(null); setMessage(""); await loadOrders(); toast({ title: "Обращение создано", description: "Поддержка увидит его вместе с заказом" }); };

  if (loading) return <main className="min-h-[70vh] pt-32 text-center text-muted-foreground">Загрузка…</main>;
  return <main className="flex-1 pt-28 pb-16"><div className="container mx-auto max-w-4xl px-4">
    <div className="mb-8 flex items-end justify-between gap-4"><div><div className="text-xs uppercase tracking-[.2em] text-[#8E1537]">Личный кабинет</div><h1 className="mt-2 text-3xl md:text-5xl font-black">Ваши покупки</h1><p className="mt-2 text-sm text-muted-foreground">Заказы, выданные данные и гарантийные обращения в одном месте.</p></div>{authenticated && <Button variant="outline" onClick={logout}><LogOut className="mr-2 h-4 w-4"/>Выйти</Button>}</div>
    {!authenticated ? <section className="mx-auto max-w-xl rounded-2xl border border-white/10 bg-white/[.035] p-5 md:p-7"><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-xl bg-[#8E1537]/10 text-[#8E1537]"><KeyRound/></div><h2 className="text-xl font-bold">Безопасный вход без пароля</h2><p className="mb-5 mt-1 text-sm text-muted-foreground">Получите одноразовый код. Если почта ещё не подключена — используйте номер любого своего заказа.</p><div className="space-y-3"><div className="relative"><Mail className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-10" type="email" placeholder="Email из заказа" value={email} onChange={e=>setEmail(e.target.value)}/></div>{emailConfigured !== null && <><Input placeholder="Код из письма" value={code} onChange={e=>setCode(e.target.value)}/><div className="text-center text-xs text-muted-foreground">или</div><Input placeholder="Номер вашего заказа" value={orderId} onChange={e=>setOrderId(e.target.value)}/></>}<div className="flex gap-2">{emailConfigured === null ? <Button className="w-full bg-[#8E1537] text-black" onClick={requestCode}>Продолжить</Button> : <><Button variant="outline" onClick={requestCode}>Отправить снова</Button><Button className="flex-1 bg-[#8E1537] text-black" onClick={login}>Войти</Button></>}</div></div></section> :
    <div className="space-y-4">{orders.length === 0 ? <div className="rounded-2xl border border-white/10 p-10 text-center"><Package className="mx-auto mb-3 text-muted-foreground"/><p>Заказов пока нет</p><Link className="mt-4 inline-block text-[#8E1537]" href="/">Перейти в каталог</Link></div> : orders.map(o => <article key={o.id} className="rounded-2xl border border-white/10 bg-white/[.025] p-5 md:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="mb-2 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-[#8E1537]/10 px-2.5 py-1 text-[#8E1537]">{STATUS[o.status] || o.status}</span><span className="px-2.5 py-1 text-muted-foreground">№ {o.id}</span></div><h2 className="text-lg font-bold">{o.productTitle}</h2><p className="text-xs text-muted-foreground">{new Date(o.createdAt).toLocaleString("ru-RU")}</p></div><strong className="text-xl text-[#8E1537]">{formatPrice(o.amount, o.currency)}</strong></div>
      <div className="my-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{o.events.map(e=><div key={e.id} className="rounded-xl border border-white/10 p-3"><div className="mb-1 flex items-center gap-2 text-xs font-semibold"><Check className="h-3.5 w-3.5 shrink-0 text-[#8E1537]"/><span className="break-words">{e.label}</span></div><div className="text-[10px] text-muted-foreground">{new Date(e.createdAt).toLocaleString("ru-RU")} · {e.actor}</div></div>)}</div>
      {o.status === "delivered" && o.login && <div className="rounded-xl border border-[#8E1537]/20 bg-[#8E1537]/[.04] p-4"><div className="mb-3 flex items-center gap-2 text-sm font-bold text-[#8E1537]"><Check className="h-4 w-4"/>Данные выданы</div>{[["Логин",o.login],["Пароль",o.password || ""]].map(([k,v])=><div className="mb-2 flex items-center gap-2" key={k}><span className="w-16 text-xs text-muted-foreground">{k}</span><code className="flex-1 break-all rounded bg-black/30 p-2 text-xs">{v}</code><button onClick={()=>copy(v)}><Copy className="h-4 w-4"/></button></div>)}<div className="mt-3 flex flex-wrap gap-2"><Button size="sm" onClick={()=>download(o)}><Download className="mr-2 h-4 w-4"/>Скачать инструкцию</Button>{new Date(o.warrantyUntil)>new Date() && <Button size="sm" variant="outline" onClick={()=>setClaimOrder(o.id)}><ShieldAlert className="mr-2 h-4 w-4"/>Проблема с товаром</Button>}</div><p className="mt-3 text-xs text-muted-foreground">Гарантия до {new Date(o.warrantyUntil).toLocaleDateString("ru-RU")}. После входа сразу смените пароль и контакты.</p></div>}
      {o.claims?.map(c=><div key={c.id} className="mt-3 rounded-xl border border-yellow-400/20 p-3 text-xs"><b>Гарантийное обращение:</b> {REASONS[c.reason as keyof typeof REASONS] || c.reason} · {c.status}{c.adminNote && <p className="mt-1 text-muted-foreground">Ответ: {c.adminNote}</p>}</div>)}
      {claimOrder===o.id && <div className="mt-4 space-y-3 rounded-xl border border-white/10 p-4"><select className="w-full rounded-md border border-white/10 bg-black p-2 text-sm" value={reason} onChange={e=>setReason(e.target.value as keyof typeof REASONS)}>{Object.entries(REASONS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><Textarea placeholder="Подробно опишите проблему (не менее 10 символов)" value={message} onChange={e=>setMessage(e.target.value)}/><div className="flex gap-2"><Button onClick={sendClaim}>Отправить</Button><Button variant="ghost" onClick={()=>setClaimOrder(null)}>Отмена</Button></div></div>}
    </article>)}</div>}
    <div className="mt-8 flex items-center gap-2 text-xs text-muted-foreground"><Clock className="h-4 w-4"/>Нужна помощь? Откройте чат поддержки — оператор увидит историю обращения. {settings.support_email}</div>
  </div></main>;
}
