"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";

type Claim = { id:string; reason:string; message:string; status:string; adminNote?:string|null; createdAt:string; order:{ id:string; buyerEmail:string; product:{title:string} } };
export function AdminWarranty(){ const [claims,setClaims]=useState<Claim[]>([]); const [notes,setNotes]=useState<Record<string,string>>({}); const load=()=>fetch("/api/warranty?admin=1").then(r=>r.json()).then(d=>setClaims(d.claims||[])); useEffect(()=>{void load()},[]);
  const update=async(id:string,status:string)=>{await fetch("/api/warranty",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status,adminNote:notes[id]||undefined})});load();};
  return <div><h1 className="text-3xl font-black mb-2">Гарантийные обращения</h1><p className="text-sm text-muted-foreground mb-6">Проблемы покупателей, автоматически связанные с заказом.</p><div className="space-y-3">{claims.map(c=><div key={c.id} className="border border-white/10 rounded-xl p-4"><div className="flex justify-between gap-3"><div><b>{c.order.product.title}</b><div className="text-xs text-muted-foreground">Заказ {c.order.id} · {c.order.buyerEmail} · {new Date(c.createdAt).toLocaleString("ru-RU")}</div></div><span className="text-xs text-[#BFFF00]">{c.status}</span></div><div className="mt-3 text-sm"><b>{c.reason}:</b> {c.message}</div><Textarea className="mt-3" placeholder="Ответ или внутренняя заметка" value={notes[c.id]??c.adminNote??""} onChange={e=>setNotes({...notes,[c.id]:e.target.value})}/><div className="flex flex-wrap gap-2 mt-3"><Button size="sm" variant="outline" onClick={()=>update(c.id,"in_progress")}>В работу</Button><Button size="sm" onClick={()=>update(c.id,"resolved")}>Решено</Button><Button size="sm" variant="destructive" onClick={()=>update(c.id,"rejected")}>Отклонить</Button></div></div>)}{!claims.length&&<p className="text-muted-foreground">Обращений нет.</p>}</div></div>;
}
