"use client";
import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Loader2, MessageSquare, Search, Send, User } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";

interface Msg { id: string; name: string; contact: string; message: string; reply?: string | null; status: string; sessionId?: string | null; createdAt: string }
const QUICK = ["Здравствуйте! Уже проверяем ваш вопрос.", "Оплата проверяется, пожалуйста, подождите несколько минут.", "Пришлите номер заказа или TX Hash.", "Вопрос решён. Если потребуется помощь — напишите снова."];

export function AdminSupport() {
  const [messages, setMessages] = useState<Msg[]>([]); const [selected, setSelected] = useState(""); const [search, setSearch] = useState(""); const [reply, setReply] = useState(""); const [loading, setLoading] = useState(true); const [online, setOnline] = useState(false); const { toast } = useToast();
  const load = async () => { const r = await fetch("/api/support"); const d = await r.json(); setMessages(d.messages || []); setLoading(false); };
  useEffect(() => { load(); fetch("/api/settings").then((r) => r.json()).then((d) => setOnline(d.settings?.operator_online === "true")); const timer = setInterval(load, 15000); return () => clearInterval(timer); }, []);
  const toggleOnline = async () => { const value = !online; await fetch("/api/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ operator_online: String(value) }) }); setOnline(value); };
  const conversations = useMemo(() => { const map = new Map<string, Msg[]>(); for (const m of messages) { const key = m.sessionId || m.contact; map.set(key, [...(map.get(key) || []), m]); } return [...map.entries()].map(([id, items]) => ({ id, items: items.sort((a,b) => +new Date(a.createdAt) - +new Date(b.createdAt)), last: items[items.length - 1], unread: items.filter((m) => m.status === "new").length })).filter((c) => `${c.last.name} ${c.last.contact} ${c.last.message}`.toLowerCase().includes(search.toLowerCase())); }, [messages, search]);
  useEffect(() => { if (!selected && conversations[0]) setSelected(conversations[0].id); }, [conversations, selected]);
  const current = conversations.find((c) => c.id === selected);
  const send = async () => { if (!current || !reply.trim()) return; const target = current.items[current.items.length - 1]; await fetch(`/api/support/${target.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reply: reply.trim(), status: "replied" }) }); setReply(""); toast({ title: "Ответ отправлен" }); load(); };
  const close = async () => { if (!current || !window.confirm("Закрыть это обращение?")) return; await Promise.all(current.items.map((m) => fetch(`/api/support/${m.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: "closed" }) }))); toast({ title: "Обращение закрыто" }); load(); };
  if (loading) return <div className="py-20 flex justify-center"><Loader2 className="animate-spin text-[#8E1537]" /></div>;
  return <div><div className="mb-5 flex items-center justify-between"><div><h1 className="text-2xl font-black uppercase">Центр поддержки</h1><p className="text-sm text-[#888] font-mono">Диалоги с покупателями · новых: {messages.filter((m) => m.status === "new").length}</p></div><Button onClick={toggleOnline} variant="outline" className={online ? "border-[#8E1537] text-[#8E1537]" : "border-[#666] text-[#888]"}><span className={cn("w-2 h-2 rounded-full mr-2", online ? "bg-[#8E1537]" : "bg-[#666]")} />{online ? "Оператор онлайн" : "Оператор офлайн"}</Button></div>
    <div className="grid lg:grid-cols-[320px_1fr] min-h-[620px] border border-[#2A2A2A] bg-[#0E0E0E]">
      <aside className="border-r border-[#2A2A2A]"><div className="p-3 border-b border-[#2A2A2A] relative"><Search className="absolute left-6 top-6 w-4 h-4 text-[#888]" /><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Поиск диалога" className="pl-9" /></div><div className="max-h-[560px] overflow-y-auto">{conversations.map((c) => <button key={c.id} onClick={() => setSelected(c.id)} className={cn("w-full p-4 text-left border-b border-[#222] hover:bg-white/5", selected === c.id && "bg-[#8E1537]/10 border-l-2 border-l-[#8E1537]")}><div className="flex justify-between gap-2"><span className="font-bold truncate">{c.last.name}</span>{c.unread > 0 && <span className="bg-[#8E1537] text-white text-[10px] px-1.5 py-0.5">{c.unread}</span>}</div><div className="text-[10px] text-[#888] font-mono truncate">{c.last.contact}</div><div className="text-xs text-[#888] truncate mt-1">{c.last.message}</div></button>)}</div></aside>
      <section className="flex flex-col">{current ? <><header className="p-4 border-b border-[#2A2A2A] flex items-center gap-3"><div className="w-9 h-9 bg-[#8E1537]/20 flex items-center justify-center"><User className="w-4 h-4 text-[#8E1537]" /></div><div className="flex-1"><div className="font-bold">{current.last.name}</div><div className="text-xs text-[#888] font-mono">{current.last.contact} · сообщений {current.items.length}</div></div><Button size="sm" variant="outline" onClick={close}><CheckCircle2 className="w-4 h-4 mr-1" />Закрыть</Button></header>
        <div className="flex-1 p-4 space-y-3 overflow-y-auto max-h-[410px]">{current.items.map((m) => <div key={m.id} className="space-y-2"><div className="max-w-[80%] bg-[#1A1A1A] border border-[#2A2A2A] p-3 text-sm"><div>{m.message}</div><div className="text-[9px] text-[#777] mt-1">{new Date(m.createdAt).toLocaleString("ru-RU")}</div></div>{m.reply && <div className="max-w-[80%] ml-auto bg-[#8E1537]/15 border border-[#8E1537]/40 p-3 text-sm"><div>{m.reply}</div><div className="text-[9px] text-[#999] mt-1">Ответ администратора</div></div>}</div>)}</div>
        <div className="p-3 border-t border-[#2A2A2A]"><div className="flex flex-wrap gap-1 mb-2">{QUICK.map((q) => <button key={q} onClick={() => setReply(q)} className="text-[10px] px-2 py-1 border border-[#333] text-[#999] hover:border-[#8E1537] hover:text-white">{q}</button>)}</div><div className="flex gap-2"><Textarea value={reply} onChange={(e) => setReply(e.target.value)} placeholder="Ответ покупателю..." rows={2} /><Button onClick={send} disabled={!reply.trim()} className="bg-[#8E1537] text-white h-auto"><Send className="w-4 h-4" /></Button></div></div></> : <div className="flex-1 flex flex-col items-center justify-center text-[#777]"><MessageSquare className="w-12 h-12 mb-3 opacity-30" />Выберите диалог</div>}</section>
    </div></div>;
}
