// ХайпХаб — seed database with demo categories and products
import { db } from "../src/lib/db";

async function main() {
  // 1. Categories
  const categories = [
    {
      id: "cat_tiktok",
      name: "TikTok аккаунты",
      slug: "tiktok",
      icon: "Music2",
      color: "#FF0050",
      platform: "tiktok",
      description: "Готовые TikTok аккаунты с подписчиками, для стрима и продвижения",
      order: 1,
    },
    {
      id: "cat_youtube",
      name: "YouTube каналы",
      slug: "youtube",
      icon: "Youtube",
      color: "#FF0000",
      platform: "youtube",
      description: "Монетизированные YouTube каналы и каналы с подписчиками",
      order: 2,
    },
    {
      id: "cat_vk",
      name: "VK группы",
      slug: "vk",
      icon: "Users",
      color: "#0077FF",
      platform: "vk",
      description: "Живые VK группы и паблики с реальной аудиторией",
      order: 3,
    },
    {
      id: "cat_instagram",
      name: "Instagram аккаунты",
      slug: "instagram",
      icon: "Instagram",
      color: "#E1306C",
      platform: "instagram",
      description: "Instagram аккаунты с активной аудиторией",
      order: 4,
    },
    {
      id: "cat_telegram",
      name: "Telegram каналы",
      slug: "telegram",
      icon: "Send",
      color: "#229ED9",
      platform: "telegram",
      description: "Telegram каналы и группы с живыми подписчиками",
      order: 5,
    },
  ];

  for (const cat of categories) {
    await db.category.upsert({
      where: { id: cat.id },
      update: cat,
      create: cat,
    });
  }

  // 2. Products
  const products = [
    {
      id: "prod_tt_1",
      categoryId: "cat_tiktok",
      title: "TikTok аккаунт 10K подписчиков",
      description: "Активный TikTok аккаунт с живой аудиторией. Подходит для стримов и продвижения. Полный доступ к почте и номеру. Возраст 6+ месяцев.",
      price: 1490,
      oldPrice: 2490,
      image: "https://images.unsplash.com/photo-1611605698335-8b1569810432?w=600&q=80",
      badges: "hot,verified",
      followers: "10K подписчиков",
      metadata: JSON.stringify({ country: "RU", age: "6 мес", monetization: false, verified: true }),
      login: "tiktok_user_10k_001@mail.com",
      password: "TT@10k#Pass2024",
      deliveryNote: "Доступ к почте и телефону прилагается. Меняйте пароль сразу после получения.",
      status: "available",
      featured: true,
    },
    {
      id: "prod_tt_2",
      categoryId: "cat_tiktok",
      title: "TikTok аккаунт 50K подписчиков",
      description: "Топовый TikTok аккаунт с аудиторией 50K. Подходит для монетизации Creator Fund. Полная гарантия и замена в течение 24 часов.",
      price: 6990,
      oldPrice: 9990,
      image: "https://images.unsplash.com/photo-1658401218713-4c5c0b0c8e74?w=600&q=80",
      badges: "top,premium",
      followers: "50K подписчиков",
      metadata: JSON.stringify({ country: "RU/CIS", age: "12 мес", monetization: true, verified: false }),
      login: "tiktok_pro_50k@mail.com",
      password: "TT@50k#Pro2024!",
      deliveryNote: "Полный доступ. Подключена монетизация. Поддержка 24/7.",
      status: "available",
      featured: true,
    },
    {
      id: "prod_tt_3",
      categoryId: "cat_tiktok",
      title: "TikTok аккаунт 100K подписчиков",
      description: "Премиум TikTok аккаунт с аудиторией 100K. Высокое вовлечение, проверенная история, готов к коммерческому использованию.",
      price: 14990,
      oldPrice: 19990,
      image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7480?w=600&q=80",
      badges: "premium,verified,top",
      followers: "100K подписчиков",
      metadata: JSON.stringify({ country: "RU", age: "18 мес", monetization: true, verified: true }),
      login: "tiktok_premium_100k@mail.com",
      password: "TT@100k#Premium!",
      deliveryNote: "VIP-поддержка, помощь с переоформлением. Гарантия 7 дней.",
      status: "available",
      featured: true,
    },
    {
      id: "prod_yt_1",
      categoryId: "cat_youtube",
      title: "YouTube канал 1000 подписчиков",
      description: "YouTube канал с 1000 подписчиков — готов к монетизации. Подходит для запуска нового проекта с уже готовой аудиторией.",
      price: 2490,
      oldPrice: 3490,
      image: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=600&q=80",
      badges: "hot",
      followers: "1000 подписчиков",
      metadata: JSON.stringify({ country: "RU", age: "8 мес", monetization: false, watchHours: 4000 }),
      login: "youtube_1k@mail.com",
      password: "YT@1k#Channel2024",
      deliveryNote: "Канал без страйков. Полный доступ к Google аккаунту.",
      status: "available",
      featured: true,
    },
    {
      id: "prod_yt_2",
      categoryId: "cat_youtube",
      title: "YouTube канал 10K подписчиков",
      description: "Монетизированный YouTube канал с 10K подписчиков. Подключена партнёрская программа. Регулярные просмотры от 5K на видео.",
      price: 8990,
      oldPrice: 12990,
      image: "https://images.unsplash.com/photo-1635262550437-cb84b16d6909?w=600&q=80",
      badges: "verified,premium",
      followers: "10K подписчиков",
      metadata: JSON.stringify({ country: "RU", age: "2 года", monetization: true, watchHours: 240000 }),
      login: "youtube_10k_monetized@mail.com",
      password: "YT@10k#Money2024!",
      deliveryNote: "Монетизация активна. Без страйков. Помощь с передачей AdSense.",
      status: "available",
      featured: true,
    },
    {
      id: "prod_yt_3",
      categoryId: "cat_youtube",
      title: "YouTube канал 100K подписчиков",
      description: "Премиум YouTube канал с аудиторией 100K. Высокий Watch Time, стабильный доход от монетизации. Полная передача с гарантией.",
      price: 49990,
      oldPrice: 69990,
      image: "https://images.unsplash.com/photo-1649296405441-a55bfce87ff2?w=600&q=80",
      badges: "premium,verified,top",
      followers: "100K подписчиков",
      metadata: JSON.stringify({ country: "RU", age: "3 года", monetization: true, watchHours: 1200000 }),
      login: "youtube_premium_100k@mail.com",
      password: "YT@100k#VIP2024!",
      deliveryNote: "VIP-передача. Помощь с переоформлением AdSense. Гарантия 14 дней.",
      status: "available",
      featured: true,
    },
    {
      id: "prod_vk_1",
      categoryId: "cat_vk",
      title: "VK группа 1000 участников",
      description: "Живая VK группа с реальными участниками. Подходит для продвижения товаров и услуг. Активность высокая.",
      price: 990,
      oldPrice: 1490,
      image: "https://images.unsplash.com/photo-1611162616305-c69b3037c7bb?w=600&q=80",
      badges: "hot",
      followers: "1000 участников",
      metadata: JSON.stringify({ country: "RU", age: "6 мес", monetization: false }),
      login: "vk_group_1k@mail.com",
      password: "VK@1k#Group2024",
      deliveryNote: "Полный доступ к создателю группы. Возможна замена в течение 24ч.",
      status: "available",
      featured: true,
    },
    {
      id: "prod_vk_2",
      categoryId: "cat_vk",
      title: "VK группа 10K участников",
      description: "Активная VK группа с 10K участников. Регулярные посты, живая аудитория, готова к монетизации через маркет.",
      price: 4990,
      oldPrice: 6990,
      image: "https://images.unsplash.com/photo-1633675254053-d96c7668c3b8?w=600&q=80",
      badges: "verified,top",
      followers: "10K участников",
      metadata: JSON.stringify({ country: "RU", age: "1.5 года", monetization: true }),
      login: "vk_group_10k@mail.com",
      password: "VK@10k#Active2024!",
      deliveryNote: "Подключена монетизация. Полные права создателя.",
      status: "available",
      featured: true,
    },
    {
      id: "prod_vk_3",
      categoryId: "cat_vk",
      title: "VK паблик 100K участников",
      description: "Топовый VK паблик с аудиторией 100K. Высокий охват, стабильный трафик. Подходит для серьёзных проектов.",
      price: 24990,
      oldPrice: 34990,
      image: "https://images.unsplash.com/photo-1611605698335-8b1569810432?w=600&q=80",
      badges: "premium,verified,top",
      followers: "100K участников",
      metadata: JSON.stringify({ country: "RU", age: "3 года", monetization: true }),
      login: "vk_public_100k@mail.com",
      password: "VK@100k#Top2024!",
      deliveryNote: "VIP-передача. Полные права. Гарантия 14 дней.",
      status: "available",
      featured: true,
    },
    {
      id: "prod_ig_1",
      categoryId: "cat_instagram",
      title: "Instagram аккаунт 5K подписчиков",
      description: "Активный Instagram аккаунт с живой аудиторией 5K. Подходит для личного бренда или бизнеса.",
      price: 1990,
      oldPrice: 2990,
      image: "https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=600&q=80",
      badges: "hot",
      followers: "5K подписчиков",
      metadata: JSON.stringify({ country: "RU", age: "8 мес", monetization: false }),
      login: "instagram_5k@mail.com",
      password: "IG@5k#Acc2024",
      deliveryNote: "Полный доступ. Email и телефон привязаны.",
      status: "available",
      featured: false,
    },
    {
      id: "prod_ig_2",
      categoryId: "cat_instagram",
      title: "Instagram аккаунт 50K подписчиков",
      description: "Премиум Instagram аккаунт с аудиторией 50K. Высокое вовлечение, готов к сотрудничеству с брендами.",
      price: 12990,
      oldPrice: 16990,
      image: "https://images.unsplash.com/photo-1620506707887-6b1f8b8e8e9e?w=600&q=80",
      badges: "premium,verified",
      followers: "50K подписчиков",
      metadata: JSON.stringify({ country: "RU/CIS", age: "2 года", monetization: true }),
      login: "instagram_50k_premium@mail.com",
      password: "IG@50k#Premium!",
      deliveryNote: "VIP-передача. Гарантия 7 дней.",
      status: "available",
      featured: true,
    },
    {
      id: "prod_tg_1",
      categoryId: "cat_telegram",
      title: "Telegram канал 1000 подписчиков",
      description: "Живой Telegram канал с реальными подписчиками. Подходит для запуска медиа-проекта.",
      price: 1490,
      oldPrice: 1990,
      image: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=600&q=80",
      badges: "hot",
      followers: "1000 подписчиков",
      metadata: JSON.stringify({ country: "RU", age: "5 мес", monetization: false }),
      login: "telegram_1k_channel",
      password: "TG@1k#Channel2024",
      deliveryNote: "Полные права администратора. Доступ к @channel.",
      status: "available",
      featured: false,
    },
    {
      id: "prod_tg_2",
      categoryId: "cat_telegram",
      title: "Telegram канал 10K подписчиков",
      description: "Активный Telegram канал с живой аудиторией. Стабильный охват постов, готов к монетизации через рекламу.",
      price: 7990,
      oldPrice: 9990,
      image: "https://images.unsplash.com/photo-1633675255779-4c2c7c8e8e8e?w=600&q=80",
      badges: "verified,top",
      followers: "10K подписчиков",
      metadata: JSON.stringify({ country: "RU", age: "1 год", monetization: true }),
      login: "telegram_10k_channel",
      password: "TG@10k#Active!",
      deliveryNote: "Подключена монетизация. Полная передача.",
      status: "available",
      featured: true,
    },
  ];

  for (const p of products) {
    await db.product.upsert({
      where: { id: p.id },
      update: p,
      create: p,
    });
  }

  // 3. FAQ
  const faqs = [
    {
      id: "faq_1",
      question: "Как купить аккаунт на ХайпХаб?",
      answer: "Выберите подходящий аккаунт в каталоге, нажмите «Купить», укажите контакт и выберите криптовалюту для оплаты (BTC, USDT, TON). После подтверждения оплаты вы мгновенно получите файл с логином и паролем на почту и в личном кабинете.",
      order: 1,
    },
    {
      id: "faq_2",
      question: "Какие способы оплаты доступны?",
      answer: "Мы принимаем оплату криптовалютой: BTC, USDT TRC-20, TON. Все способы — анонимны, без проверки личности. Крипто-платежи проходят за 1–15 минут в зависимости от монеты (TON — самый быстрый, BTC — самый надёжный).",
      order: 2,
    },
    {
      id: "faq_3",
      question: "Даёте ли вы гарантию на аккаунты?",
      answer: "Да. На все аккаунты действует гарантия от 24 часов до 14 дней в зависимости от категории. Если в течение гарантийного срока возникнут проблемы с доступом — мы заменим аккаунт или вернём средства.",
      order: 3,
    },
    {
      id: "faq_4",
      question: "Как быстро я получу данные после оплаты?",
      answer: "Мгновенно. Сразу после подтверждения оплаты вы получаете файл .txt с логином, паролем и инструкцией по безопасному входу. Файл доступен в личном кабинете и дублируется на email.",
      order: 4,
    },
    {
      id: "faq_5",
      question: "Это законно — покупать аккаунты?",
      answer: "Покупка и продажа аккаунтов не запрещена законом РФ. Мы рекомендуем сразу сменить пароль, привязать свои контакты и включить двухфакторную аутентификацию для безопасности.",
      order: 5,
    },
    {
      id: "faq_6",
      question: "Что если аккаунт не подойдёт?",
      answer: "Если аккаунт не соответствует описанию или появились проблемы с доступом в течение гарантийного срока — напишите в чат поддержки. Мы заменим аккаунт или оформим возврат в течение 24 часов.",
      order: 6,
    },
    {
      id: "faq_7",
      question: "Могу ли я получить помощь с настройкой?",
      answer: "Да, наш AI-ассистент на сайте поможет с любым вопросом 24/7. Для сложных случаев работает живой чат техподдержки — пишите, поможем с входом, настройкой безопасности и монетизацией.",
      order: 7,
    },
  ];

  for (const f of faqs) {
    await db.faqItem.upsert({
      where: { id: f.id },
      update: f,
      create: f,
    });
  }

  // 4. Settings
  const settings = [
    { id: "set_site_name", key: "site_name", value: "ХайпХаб" },
    { id: "set_tagline", key: "tagline", value: "Маркетплейс аккаунтов TikTok, YouTube и VK" },
    { id: "set_crypto_btc", key: "crypto_btc", value: "bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh" },
    { id: "set_crypto_usdt", key: "crypto_usdt", value: "TXkNQ6MeYF3G7kC7p2eQ8fY2rZyW5kJ9hN" },
    { id: "set_crypto_ton", key: "crypto_ton", value: "EQDrjaLahLkMB-hMCmkzOyBuHJ139QHbPPHu2qWQ4g2v5k2H" },
    { id: "set_admin_pass", key: "admin_pass", value: "hypehub2024" },
    { id: "set_email", key: "support_email", value: "support@hypehub.vercel.app" },
    { id: "set_telegram", key: "support_telegram", value: "@hypehub_support" },
    { id: "set_stats_accounts", key: "stats_accounts", value: "5 200+" },
    { id: "set_stats_clients", key: "stats_clients", value: "12 800+" },
    { id: "set_stats_rating", key: "stats_rating", value: "4.9" },
    { id: "set_stats_support", key: "stats_support", value: "24/7" },
  ];

  for (const s of settings) {
    await db.setting.upsert({
      where: { id: s.id },
      update: s,
      create: s,
    });
  }

  console.log("✅ Seed completed");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
